services:
  postgres-db:
    image : postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports: 
      - "127.0.0.1:5432:5432"
    volumes:
      - jpa_vol:/var/lib/postgresql/data
    networks:
      - jpa_net
  cpo2_jpa:
    build: .
    depends_on:
      - postgres-db
    networks:
      - jpa_net
volumes:
  jpa_vol:
networks:
  jpa_net: 